name: Update M3U

on:
  schedule:
    - cron: "0 */2 * * *"   # her 2 saatte bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.39.1  # sabitleyebilirsin
          # İndirme aşağıdaki adımda yapılacak (çıktı genişliğini azaltmak için ayrı)
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Run generator
        run: python generate_m3u_playwright.py
        env:
          # Opsiyonel: Bazı siteler için LANG gerekebilir
          LANG: "en_US.UTF-8"

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 1UmitTV.m3u || true
          git commit -m "Update M3U" || echo "No changes to commit"
          git push || echo "Push failed"
