name: Update M3U

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Ensure M3U file exists
        run: |
          if [ ! -f 1UmitTV.m3u ]; then
            echo "#EXTM3U" > 1UmitTV.m3u
          fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip & Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run M3U generator
        run: python generate_m3u.py
        env:
          LANG: "en_US.UTF-8"

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github-actions"
          git add 1UmitTV.m3u
          if ! git diff --cached --quiet; then
            git commit -m "Update M3U"
            git push
          else
            echo "No changes to commit"
