name: Update dbdM3U

on:
  schedule:
    - cron: "0 */2 * * *"   # her 2 saatte bir çalıştır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip & Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright          # en güncel sürüm kurulacak

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run M3U generator
        run: python generate_m3u_playwright.py
        env:
          LANG: "en_US.UTF-8"

      - name: Commit & push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add 1UmitTV.m3u || true
          git commit -m "Update M3U" || echo "No changes to commit"
          git push || echo "Push failed"
