name: Update qdene.json every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte 1 UTC zamanı

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies (if any)
      run: |
        python -m pip install --upgrade pip

    - name: Run script.py
      run: |
        python script.py

    - name: Commit and push changes
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add qdene.json
        git diff --cached --quiet || git commit -m "Update qdene.json [skip ci]"
        git push
