name: Update qdene.json every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *' # 6 saatte bir
  workflow_dispatch:     # Manuel çalıştırma için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python script.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add qdene.json
          git diff --cached --quiet || git commit -m "Auto-update qdene.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
